---
- name: Install and start rke2
  hosts: localhost
  become: true
  tasks:
    - name: Download rke2 installation script
      ansible.builtin.get_url:
        url: https://get.rke2.io
        dest: /tmp/install_rke2.sh
        mode: '0700'

    - name: Install rke2 as server
      ansible.builtin.shell:
        cmd: |
          INSTALL_RKE2_CHANNEL="latest" /tmp/install_rke2.sh
      changed_when: true

    - name: Start the rke2-server service
      ansible.builtin.service:
        name: rke2-server
        enabled: true
        state: started

    - name: Create symlink for kubectl
      ansible.builtin.file:
        src: /var/lib/rancher/rke2/bin/kubectl
        dest: /usr/local/bin/kubectl
        state: link
        force: true

    - name: Create .kube/ folder
      ansible.builtin.file:
        path: /home/ubuntu/.kube
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Copy kubeconfig to ~/.kube/
      ansible.builtin.copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'

- name: Install Helm
  hosts: localhost
  become: true
  tasks:
    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Install Helm
      ansible.builtin.shell:
        cmd: |
          /tmp/get_helm.sh
      changed_when: true

    - name: Download helmfile binary
      ansible.builtin.unarchive:
        src: https://github.com/helmfile/helmfile/releases/download/v0.170.1/helmfile_0.170.1_linux_amd64.tar.gz
        dest: /usr/local/bin/
        mode: '0755'
        remote_src: true
        include:
          - helmfile
