on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check OpenTofu file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tofu fmt
        uses: dflook/tofu-fmt-check@v1
        id: fmt-check

  validate:
    runs-on: ubuntu-latest
    name: Validate OpenTofu module
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tofu validate
        uses: dflook/tofu-validate@v1
        id: validate
